STD_PADDING = 5
TAB_Y_PADDING = STD_PADDING
TAB_X_PADDING = STD_PADDING

BLUE_COLOR = "#3B8ED0"
TRANSPARENT_COLOR = "transparent"
DEFAULT_APPEARANCE_MODE = "Dark"
DEFAULT_COLOR_THEME = "blue"

BASE_WINDOW_WIDTH = 2560
BASE_WINDOW_HEIGHT = 1440

DEFAULT_APP_SCALING = 1.4
